// angular-ui/src/app/lobby/lobby.component.ts
import { Component } from '@angular/core';
import { SocketService } from '../services/socket.service';
import { CommonModule } from '@angular/common';
import { GameDataService } from '../services/game-data.service';

@Component({
  selector: 'app-lobby',
  imports: [CommonModule],
  templateUrl: './lobby.component.html',
  styleUrl: './lobby.component.scss',
})
export class LobbyComponent {
  public name: string = "";
  public team: string = "";
  public error: string = "";
  public game_state: any = null;

  constructor(private socket: SocketService, private gameDataService: GameDataService) {}

  ngOnInit(): void {
    this.gameDataService.gameState.subscribe((game_state: any) => {
      this.game_state = game_state;
    }); 
  }

  public join() {
    this.socket.emit('join_game', { name: this.name, team: this.team });
  }

  public startGame() {
    this.socket.emit('start_game', '');
  }
}

<p>lobby works!</p>
<div>
    <h2>Lobby</h2>
    <input placeholder="Enter your name" [value]="name" />
    <select [value]="team">
        <option value="team1">Team 1</option>
        <option value="team2">Team 2</option>
        <option value="neutral">Neutral</option>
    </select>
    <button (click)="join()">Join Game</button>
    <p style="color: 'red'" *ngIf="error != ''">{{ error }}</p>
    <div className="mt-4">
        <div *ngFor="let team of game_state.teams">
            <h3>team</h3>
            <ul>
                <li *ngFor="let player of game_state.teams[team]">
                    {{ player["name"] || player["sid"] }}
                </li>
            </ul>
        </div>
    </div>
    <button className="mt-4" (click)="startGame()">Start Game</button>
</div>

// ui/src/components/Lobby.jsx
// Full-stack Battleground Lanka - Frontend (React) + Backend (FastAPI)

// File: src/components/Lobby.jsx
import React, { useState, useEffect } from "react";
import { useSelector } from "react-redux";

export default function Lobby({ socket, startGame }) {
  const gameState = useSelector((state) => state.game.gameState);
  const playerId = useSelector((state) => state.game.playerId);
  const [name, setName] = useState("");
  const [team, setTeam] = useState("team1");
  const [error, setError] = useState(null);
  useEffect(() => {
    console.log("Lobby:: Redux gameState updated:", gameState);
  }, [gameState]);

  useEffect(() => {
    socket.on("error", (data) => {
      setError(data.message);
    });
    // socket.on("lobby_update", (data) => {
    //   setGameState(() => ({
    //     teams: data.teams,
    //     players: data.players,
    //   }));
    // });

    return () => {
      // socket.off("lobby_update");
      socket.off("error");
    };
  }, [socket]);

  const join = () => {
    socket.emit("join_game", { name, team });
  };

  const renderTeam = (teamName) => {
    return (
      <div>
        <h3>{teamName.toUpperCase()}</h3>
        <ul>
          {(gameState?.teams[teamName] || []).map((obj) => (
            <li key={obj["sid"]}>{obj["name"] || obj["sid"]}</li>
          ))}
        </ul>
      </div>
    );
  };

  return (
    <div>
      <h2>Lobby</h2>
      <input
        placeholder="Enter your name"
        value={name}
        onChange={(e) => setName(e.target.value)}
      />
      <select value={team} onChange={(e) => setTeam(e.target.value)}>
        <option value="team1">Team 1</option>
        <option value="team2">Team 2</option>
        <option value="neutral">Neutral</option>
      </select>
      <button onClick={join}>Join Game</button>
      {error && <p style={{ color: "red" }}>{error}</p>}
      <div className="mt-4">
        {renderTeam("team1")}
        {renderTeam("team2")}
        {renderTeam("neutral")}
      </div>
      <button className="mt-4" onClick={startGame}>Start Game</button>
    </div>
  );
}
